[package]
name = "ditherpunker"
version = "0.2.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.9"
# TODO: replace with serde
json = "0.12.4"
rand = "0.9.2"
